### ISSUE TITLE
Can't find '_main_' module in 'C:\program files\\Inkscape'.

### ISSUE THREAD

**Issue by pkhardage** [camrbuss/nodes_to_csv#1]
Export does not work for CSV.

**Comment by camrbuss** [comment]
I just updated the code for inkscape 1.2. What version are you running? Can you test with the new code?

**Comment by pkhardage** [comment]
Thanks for your reply. I am on inkscape 1.2.2 with the Can't find '_main_' module issue.

Kent Hardage

**Comment by pkhardage** [comment]
The last issue about_main_ was on my laptop using version 1.2.2 inkscape.
I loaded version 1.2.2 on my workstation and did not have this issue but had another issue. PermissionError[Errno13] Permission denied: 'directory\points.cvs'

Kent Hardage

**Comment by camrbuss** [comment]
Make sure `directory\points.cvs` is a valid directory. If you are on Windows, maybe `%temp%\points.csv` would be a good start

**Comment by pkhardage** [comment]
Cam, thank you for your response. You have encouraged me to keep working on getting this inkscape extension working and it is now working properly! I can now get path x,y points into a spreadsheet. I now have to process the "nodes" into a direction(angle) and distance vector to drive my robotic welder project. It is unique in that I have to know the direction it needs to move to rotate the welder coordinate system to weld in the direction it is moving. Quite different from a laser or router which is symmetrical in all directions. My next goal is to be able to weld script text with output from inkscape and nodes_to_csv.

Thanks,  Kent Hardage

**Comment by camrbuss** [comment]
Glad it helped!
